services:
  pgadmin:
    image: dpage/pgadmin4:9.2.0
    container_name: pgadmin-nttc
    ports:
      - "2345:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: nttc@fakemail123.com
      PGADMIN_DEFAULT_PASSWORD: Nttc1234
    restart: unless-stopped
  postgres:
    build: ./postgres
    container_name: postgres-nttc
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: nttc4
    restart: unless-stopped